const $=s=>document.querySelector(s);let tasks=[],filter='all',editing=null;
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||'Something went wrong.');return data}
function fmtDate(s){if(!s)return'';return new Date(s.length===10?s+'T12:00:00':s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
async function load(){tasks=await api('/api/tasks');render()}
function render(){const q=$('#search').value.toLowerCase();const visible=tasks.filter(t=>(filter==='all'||t.status===filter)&&(!q||[t.title,t.notes,t.next_action,t.project].some(v=>(v||'').toLowerCase().includes(q))));for(const s of ['inbox','active','backlog','completed'])$('#count-'+s).textContent=tasks.filter(t=>t.status===s).length;$('#count-all').textContent=tasks.length;$('#task-summary').textContent=`${visible.length} task${visible.length===1?'':'s'}`;$('#task-list').innerHTML=visible.length?visible.map(t=>`<article class="task" data-id="${t.id}" data-status="${t.status}"><button class="complete" title="${t.status==='completed'?'Return to Active':'Complete task'}"></button><div><h3>${escapeHtml(t.title)}${t.is_accomplishment?' ★':''}</h3><div class="meta"><span class="pill">${t.status[0].toUpperCase()+t.status.slice(1)}</span>${t.project?`<span>${escapeHtml(t.project)}</span>`:''}${t.target_date?`<span class="pill due">Due ${fmtDate(t.target_date)}</span>`:''}${t.completed_at?`<span>Completed ${fmtDate(t.completed_at)}</span>`:''}${t.next_action?`<span>Next: ${escapeHtml(t.next_action)}</span>`:''}</div></div><button class="edit">Edit</button></article>`).join(''):`<div class="empty"><h2>Nothing here yet</h2><p>Add a task or try the command box above.</p></div>`}
function openTask(task=null){editing=task;$('#dialog-title').textContent=task?'Edit task':'New task';$('#task-id').value=task?.id||'';$('#title').value=task?.title||'';$('#status').value=task?.status||'inbox';$('#target-date').value=(task?.target_date||'').slice(0,10);$('#project').value=task?.project||'';$('#next-action').value=task?.next_action||'';$('#notes').value=task?.notes||'';$('#accomplishment').checked=!!task?.is_accomplishment;$('#history').innerHTML='';if(task)loadHistory(task.id);$('#task-dialog').showModal();setTimeout(()=>$('#title').focus(),50)}
async function loadHistory(id){const items=await api(`/api/tasks/${id}/history`);$('#history').innerHTML='<strong>History</strong>'+items.slice(0,6).map(e=>`<p>${fmtDate(e.occurred_at)} · ${escapeHtml(e.event_type)} via ${escapeHtml(e.source)}</p>`).join('')}
async function save(e){e.preventDefault();const data={title:$('#title').value,status:$('#status').value,target_date:$('#target-date').value||null,project:$('#project').value||null,next_action:$('#next-action').value||null,notes:$('#notes').value||null,is_accomplishment:$('#accomplishment').checked};await api(editing?`/api/tasks/${editing.id}`:'/api/tasks',{method:editing?'PATCH':'POST',body:JSON.stringify(data)});$('#task-dialog').close();await load()}
async function runCommand(){const input=$('#command'),text=input.value.trim();if(!text)return;$('#send').disabled=true;try{const result=await api('/api/command',{method:'POST',body:JSON.stringify({text})});$('#command-result').textContent=result.message;input.value='';await load()}catch(e){$('#command-result').textContent=e.message}finally{$('#send').disabled=false}}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.status;$('#page-title').textContent=b.querySelector('span').textContent;render()});
$('#task-list').addEventListener('click',async e=>{const card=e.target.closest('.task');if(!card)return;const task=tasks.find(t=>t.id===card.dataset.id);if(e.target.classList.contains('complete')){await api(`/api/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:task.status==='completed'?'active':'completed'})});await load()}else openTask(task)});
$('#new-task').onclick=()=>openTask();$('#close').onclick=$('#cancel').onclick=()=>$('#task-dialog').close();$('#task-form').addEventListener('submit',save);$('#send').onclick=runCommand;$('#command').addEventListener('keydown',e=>{if(e.key==='Enter')runCommand()});$('#search').addEventListener('input',render);$('#date-line').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});load().catch(e=>$('#task-list').innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`);

